---
- name: Make sure packages are installed
  become: true
  apt:
    name:
      - parted
      - xfsprogs
    state: present

- name: Check if mounted
  become: true
  raw: mount
  register: mnt_out
  ignore_errors: yes
  when: true

- name: Unmount device, if mounted
  become: true
  mount:
    name: "{{ mnt_dir }}"
    state: unmounted
  when: "mnt_dir in mnt_out.stdout"

- name: Test if the partition already exists
  command: lsblk -o NAME | grep {{ partition_name }}
  become: true
  ignore_errors: true
  register: part_tst
  when: true

- name: Partition the new storage
  become: true
  command: parted -s {{ device_path }} mklabel gpt mkpart primary {{ partition_type }} 0% 100%
  when: not part_tst.stdout

- name: Get TYPE
  become: true
  command: blkid -s TYPE -o value {{ partition_path }}
  register: type_out
  when: true

- name: Set FS Type
  set_fact:
    fs_type_curr: "{{ type_out.stdout }}"

- name: Make the "{{ partition_type }}" File System
  become: true
  raw: mkfs.{{ partition_type }} {{ partition_path }} -f
  when: fs_type_curr is undefined or fs_type_curr | length == 0 or fs_type_curr != partition_type

- name: get mount stats
  stat:
    path: "{{ mnt_dir }}"
  register: st

- name: Kill {{ mnt_dir }} if it exists
  file:
    path: "{{ mnt_dir }}"
    state: absent
  become: true

- name: Mount up device to get uuid
  become: true
  mount:
    name: "{{ mnt_dir }}"
    src: "{{ partition_path }}"
    fstype: "{{ partition_type }}"
    opts: "rw,relatime,data=ordered"
    state: present

- name: Get UUID
  command: blkid -s UUID -o value {{ partition_path }}
  register: uuid_out
  become: true
  when: true

- name: Set UUID
  set_fact:
    uuid: "{{ uuid_out.stdout }}"

- name: Set ext4 mount options
  set_fact:
    mount_opts: rw,relatime,data=ordered
  when: partition_type == "ext4"

- name: Set xfs mount options
  set_fact:
    mount_opts: rw,relatime,attr2,inode64,noquota
  when: partition_type == "xfs"

- name: Unmount device
  become: true
  mount:
    name: "{{ mnt_dir }}"
    state: absent

- name: Mount device and save to fstab
  become: true
  mount:
    name: "{{ mnt_dir }}"
    src: "UUID={{ uuid }}"
    fstype: "{{ partition_type }}"
    opts: "{{ mount_opts }}"
    state: mounted
